language: go
go: 1.10.2
before_install: go get -u golang.org/x/vgo
install: vgo vendor
script:
  - vgo build -o golog .
  - vgo test -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success: bash <(curl -s https://codecov.io/bash)