language: go
go: 1.10.2
before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go get github.com/mattn/goveralls
  - go get github.com/magefile/mage
install: dep ensure
script:
  - mage all
after_success:
  - goveralls -coverprofile=coverage.text -service=travis-ci
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false